language: go
go:
- 1.13
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/onsi/ginkgo/ginkgo  
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
script:
- "$HOME/gopath/bin/ginkgo -r -cover"
- "cat tcp/tcp.coverprofile > timeout.coverprofile"
- "cat http/http.coverprofile | grep -v \"mode: atomic\" >> timeout.coverprofile"
- "$HOME/gopath/bin/goveralls -coverprofile=timeout.coverprofile -service=travis-ci"
- "rm timeout.coverprofile http/http.coverprofile tcp/tcp.coverprofile"
